name: Check Package Version
description: Checks if the package version has been updated compared to a specified branch.
author: Arnau Villoro

inputs:
  repository:
    description: Repository to check version in
    required: true
    default: ${{ github.repository }}

  ref:
    description: Branch reference
    required: true
    default: ${{ github.ref }}

  branch:
    description: Branch to compare the version with
    required: false
    default: main

  file:
    description: File to check version in (e.g., pyproject.toml, version.json)
    required: false
    default: pyproject.toml

  path:
    description: Path inside the file to extract the version
    required: false
    default: project/version

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Target Branch
      run: git fetch origin ${{ inputs.branch }} --depth=1
      shell: bash

    - name: Install Dependencies
      run: pip install toml loguru packaging click pyyaml
      shell: bash

    - name: Run Version Check
      run: python $GITHUB_ACTION_PATH/check_version.py --branch=${{ inputs.branch }} --file=${{ inputs.file }} --path=${{ inputs.path }}
      shell: bash
